### ISSUE TITLE
max_kcpu_usage(eosjs-api)  => max_cpu_usage_ms (eos)

### ISSUE THREAD

**Issue by yepp4you** [EOSIO/eosjs-api#10]
The headers' key name appears to be different from the recent code in eos

//  libraries/chain/eosio_contract_abi.cpp (EOS)
   eos_abi.structs.emplace_back( struct_def {
      "transaction_header", "", {
         {"expiration", "time_point_sec"},
         {"ref_block_num", "uint16"},
         {"ref_block_prefix", "uint32"},
         {"max_net_usage_words", "varuint32"},
         {"max_cpu_usage_ms", "uint8"},
         {"delay_sec", "varuint32"}
      }
   });

// src/exported-helpers.js (eosjs-api)
    api.getBlock(info.head_block_num - 3, checkError(callback, block => {
      const expiration = new Date(chainDate.getTime() + expireInSeconds * 1000)
      const headers = {
        expiration: expiration.toISOString().split('.')[0],
        region: 0,
        ref_block_num,
        ref_block_prefix: block.ref_block_prefix,
        max_net_usage_words: 0,
        max_kcpu_usage: 0,
        delay_sec: 0,
        context_free_actions: [],
        actions: [],
        signatures: [],

**Comment by jcalfee** [comment]
Please try the latest version .. It is compatible with eosio/eos:dawn-v4.0.0 ..
