### ISSUE TITLE
It seems that abi information is not updated.

### ISSUE THREAD

**Issue by yepp4you** [EOSIO/eosjs-api#11]
// eos/libraries/chain/eosio_contract_abi.cpp 
   eos_abi.structs.emplace_back( struct_def {
      "transaction_header", "", {
         {"expiration", "time_point_sec"},
         {"ref_block_num", "uint16"},
         {"ref_block_prefix", "uint32"},
         {"max_net_usage_words", "varuint32"},
         {"max_cpu_usage_ms", "uint8"},
         {"delay_sec", "varuint32"}
      }
   });

https://github.com/EOSIO/eosjs-api/blob/5224755337b3f8e9e76a7e6d94fe0a9e35cc4746/src/exported-helpers.js#L59

**Comment by jcalfee** [comment]
duplicate: https://github.com/EOSIO/eosjs-api/issues/10
