### ISSUE TITLE
Could you add get_producers to chain.json ?

### ISSUE THREAD

**Issue by yepp4you** [EOSIO/eosjs-api#12]
"get_producers": {
    "brief": "Fetch smart contract data from producer.",
    "params": {
      "json": { "type": "bool", "default": false},
      "lower_bound": {"type": "string", "default": "0"},
      "limit": {"type": "uint32", "default": "10"}
    },
    "results": {
      "rows": {
        "type": "vector",
        "doc": "one row per item, either encoded as hex String or JSON object"
      },
      "total_producer_vote_weight":{
        "type": "float64",
        "doc": "total vote"
      },
      "more": {
        "type": "bool",
        "doc": "true if last element"
      }
    }
  },

https://github.com/EOSIO/eosjs-api/blob/1b9f2f6fb8118f58d77aec544ac6eaf4a3686fbf/src/api/v1/chain.json#L94

**Comment by jcalfee** [comment]
Added and published to npm under eosjs-api@6.0.1
