### ISSUE TITLE
Issue encounter while connecting js to blockchain project

### ISSUE THREAD

**Issue by SheldonHH** [EOSIO/eosjs-api#2]
![image](https://user-images.githubusercontent.com/16319106/34299097-0efd405e-e75c-11e7-8f62-448b6ca0778e.png)
Expecting hex string or buffer in `message.data`
https://github.com/EOSIO/eosjs-api/blob/e9ce1e57911e33560bc481e158a9254c44d3f771/src/apigen.js#L94

**Comment by jcalfee** [comment]
I think that line is working as intended.  

eosjs-api is for read only .. you should use eosjs for transactions: http://github.com/eosio/eosjs
