### ISSUE TITLE
/v1/history/get_key_accounts

### ISSUE THREAD

**Issue by mohit-lala** [EOSIO/eosjs-api#22]
get_key_accounts endpoint not working, Always shows 404 not found,
for testnet
account name : lalaworld131
public key : EOS6FxXbikY5ZUN9qEdeLbEYLKZzJwRYRr2PuC3rqfSu67LvhPARi
not able to map public key to account name using this API

**Comment by jeffreyssmith2nd** [comment]
404 not found means the node you are running against doesn't have the history plugin enabled.
