### ISSUE TITLE
How can I call a function that I have defined in the contract from my js ?

### ISSUE THREAD

**Issue by Vyshakhcs1** [EOSIO/eosjs-api#8]
My target is to make an app that can be html or native. For now let it be web app. I have deployed a hello world contract in my local blockchain network. I have defined a function named "hi". I need to call this function from my web app through js and I'm using **eosjs** in **browserify**. Can anyone guide me through this ? It would be great if anyone can give me a solution here.

**Comment by jcalfee** [comment]
duplicate: https://github.com/EOSIO/eosjs/issues/61
