### ISSUE TITLE
Feature Request: Ability to silence throws and error logs for apigen

### ISSUE THREAD

**Issue by nsjames** [EOSIO/eosjs-api#9]
This is primarily for tests which assert on failures.

for instance something like:
```
const shouldFail = await contract.fails().catch(() => {});
assert(!shouldFail, "Err");
```
will fail successfully but still throw/log the error and clutters the test results.

**Comment by nsjames** [comment]
I think maybe it should even be passable to actions themselves and not the global object so that errors can still be displayed globally for testing when using non-failure assertions. Otherwise the developer would have to keep flipping the boolean and parse through all the failure errors to find the relevant one they are working on.

**Comment by jcalfee** [comment]
The npm `debug` package is good but it adds 20k in size..  We can probably do something smaller that fits the purpose better.

**Comment by jcalfee** [comment]
See options.logger:
https://github.com/EOSIO/eosjs-api#configuration

Will this work?

**Comment by nsjames** [comment]
Yeah man, that looks fantastic.
